### ISSUE TITLE
Help.Js 

### ISSUE THREAD

**Issue by onlinezc** [RainyXeon/Cylane#20]
Slash commands is not working

CombinedPropertyError (1)
  Received one or more errors
  input[0]
  | CombinedPropertyError (1)
  |   Received one or more errors
  | 
  |   input.value
  |   | ExpectedConstraintError > s.string.lengthGreaterThanOrEqual
  |   |   Invalid string length
  |   | 
  |   |   Expected: expected.length >= 1
  |   | 
  |   |   Received:
  |   |   | ''
    at ArrayValidator.handle (/home/container/node_modules/@discordjs/builders/node_modules/@sapphire/shapeshift/dist/index.js:468:70)
    at ArrayValidator.parse (/home/container/node_modules/@discordjs/builders/node_modules/@sapphire/shapeshift/dist/index.js:207:88)
    at EmbedBuilder.addFields (/home/container/node_modules/@discordjs/builders/dist/index.js:209:31)
    at /home/container/src/commands/slash/Info/Help.js:24:23
    at Array.forEach (<anonymous>)
    at Object.run (/home/container/src/commands/slash/Info/Help.js:20:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:28) DeprecationWarning: The SelectMenuBuilder class is deprecated. Use StringSelectMenuBuilder instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:28) DeprecationWarning: The SelectMenuOptionBuilder class is deprecated. Use StringSelectMenuOptionBuilder instead.
(node:28) DeprecationWarning: BaseInteraction#isSelectMenu() is deprecated. Use BaseInteraction#isStringSelectMenu() instead.
04-04-2023 12:46:42 - ERROR   - Error: Received one or more errors
{
  level: 'error',
  message: CombinedPropertyError (1)
    Received one or more errors
  
    input[0]
    | [CombinedPropertyError]
  
      at ArrayValidator.handle (/home/container/node_modules/@discordjs/builders/node_modules/@sapphire/shapeshift/dist/index.js:468:70)
      at ArrayValidator.parse (/home/container/node_modules/@discordjs/builders/node_modules/@sapphire/shapeshift/dist/index.js:207:88)
      at EmbedBuilder.addFields (/home/container/node_modules/@discordjs/builders/dist/index.js:209:31)
      at InteractionCollector.<anonymous> (/home/container/src/commands/slash/Info/Help.js:65:34)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
  timestamp: '04-04-2023 12:46:42'
}

**Comment by RainyXeon** [comment]
Please use this commit  https://github.com/RainyXeon/Cylane/commit/4c0c45d5d7c5375adfe85b44a9e7db4390b3f4b0 while I was fixing.

**Comment by RainyXeon** [comment]
@onlinezc Now fixed on https://github.com/RainyXeon/Cylane/commit/840657cd7402aac758d31190a3f261b249479fb7 commit
