### ISSUE TITLE
there's an issues with mongoose 

### ISSUE THREAD

**Issue by onlinezc** [RainyXeon/Cylane#29]
20-05-2023 02:05:54 - ERROR   - MongooseError: Operation `premia.find()` buffering timed out after 10000ms
{
  level: 'error',
  message: MongooseError: Operation `premia.find()` buffering timed out after 10000ms
      at Timeout.<anonymous> (/home/container/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7),
  timestamp: '20-05-2023 02:05:54'
}
20-05-2023 02:05:54 - ERROR   - MongooseError: Operation `reconnects.find()` buffering timed out after 10000ms
{
  level: 'error',
  message: MongooseError: Operation `reconnects.find()` buffering timed out after 10000ms
      at Timeout.<anonymous> (/home/container/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7),
  timestamp: '20-05-2023 02:05:54'
}
20-05-2023 02:06:13 - ERROR   - MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
{
  level: 'error',
  message: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
      at _handleConnectionErrors (/home/container/node_modules/mongoose/lib/connection.js:792:11)
      at NativeConnection.openUri (/home/container/node_modules/mongoose/lib/connection.js:767:11)
      at async module.exports (/home/container/src/handlers/Database/loadDatabase.js:7:9) {
    reason: TopologyDescription {
      type: 'ReplicaSetNoPrimary',
      servers: Map(3) {
        'cluster0-shard-00-00.jqlhx.mongodb.net:27017' => ServerDescription {
          address: 'cluster0-shard-00-00.jqlhx.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 1686978133,
          lastWriteDate: 0,
          error: MongoNetworkError: getaddrinfo EAI_AGAIN cluster0-shard-00-00.jqlhx.mongodb.net
              at connectionFailureError (/home/container/node_modules/mongodb/lib/cmap/connect.js:370:20)
              at TLSSocket.<anonymous> (/home/container/node_modules/mongodb/lib/cmap/connect.js:293:22)
              at Object.onceWrapper (node:events:628:26)
              at TLSSocket.emit (node:events:513:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: getaddrinfo EAI_AGAIN cluster0-shard-00-00.jqlhx.mongodb.net
                at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
              errno: -3001,
              code: 'EAI_AGAIN',
              syscall: 'getaddrinfo',
              hostname: 'cluster0-shard-00-00.jqlhx.mongodb.net'
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'cluster0-shard-00-01.jqlhx.mongodb.net:27017' => ServerDescription {
          address: 'cluster0-shard-00-01.jqlhx.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 1686978117,
          lastWriteDate: 0,
          error: MongoNetworkError: getaddrinfo EAI_AGAIN cluster0-shard-00-01.jqlhx.mongodb.net
              at connectionFailureError (/home/container/node_modules/mongodb/lib/cmap/connect.js:370:20)
              at TLSSocket.<anonymous> (/home/container/node_modules/mongodb/lib/cmap/connect.js:293:22)
              at Object.onceWrapper (node:events:628:26)
              at TLSSocket.emit (node:events:513:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: getaddrinfo EAI_AGAIN cluster0-shard-00-01.jqlhx.mongodb.net
                at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
              errno: -3001,
              code: 'EAI_AGAIN',
              syscall: 'getaddrinfo',
              hostname: 'cluster0-shard-00-01.jqlhx.mongodb.net'
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'cluster0-shard-00-02.jqlhx.mongodb.net:27017' => ServerDescription {
          address: 'cluster0-shard-00-02.jqlhx.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 1686978161,
          lastWriteDate: 0,
          error: MongoNetworkError: getaddrinfo EAI_AGAIN cluster0-shard-00-02.jqlhx.mongodb.net
              at connectionFailureError (/home/container/node_modules/mongodb/lib/cmap/connect.js:370:20)
              at TLSSocket.<anonymous> (/home/container/node_modules/mongodb/lib/cmap/connect.js:293:22)
              at Object.onceWrapper (node:events:628:26)
              at TLSSocket.emit (node:events:513:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: getaddrinfo EAI_AGAIN cluster0-shard-00-02.jqlhx.mongodb.net
                at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
              errno: -3001,
              code: 'EAI_AGAIN',
              syscall: 'getaddrinfo',
              hostname: 'cluster0-shard-00-02.jqlhx.mongodb.net'
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        }
      },
      stale: false,
      compatible: true,
      heartbeatFrequencyMS: 10000,
      localThresholdMS: 15,
      setName: 'atlas-awlx21-shard-0',
      maxElectionId: null,
      maxSetVersion: null,
      commonWireVersion: 0,
      logicalSessionTimeoutMinutes: null
    },
    code: undefined
  },
  timestamp: '20-05-2023 02:06:13'
}

**Comment by RainyXeon** [comment]
Check the network tab to make sure the `0.0.0.0` is whitelisted 
![Uploading Screenshot_20230520-134354_Chrome.png…]()

**Comment by RainyXeon** [comment]
![Screenshot_20230520-134354_Chrome](https://github.com/RainyXeon/Cylane/assets/86668725/23ebe231-372a-456c-a93a-f70686ca588b)

**Comment by onlinezc** [comment]
I already did that but still not working
I

**Comment by onlinezc** [comment]
![Screenshot 2023-05-28 135355](https://github.com/RainyXeon/Cylane/assets/101080694/3dd6f481-ffd2-4a15-aeec-4d19eaea9c66)

**Comment by RainyXeon** [comment]
@onlinezc Have you checked the format of mongo uri link? Make sure it not have the `<>` in username and password

**Comment by RainyXeon** [comment]
@onlinezc can you tell me more details

**Comment by onlinezc** [comment]
![Screenshot 2023-06-18 203916](https://github.com/RainyXeon/Cylane/assets/101080694/a0e4f3ba-4ed3-4114-b8db-9d1cc2bf59f5)

I'm getting this error

**Comment by RainyXeon** [comment]
@onlinezc ok clone the `version-mongoose` branch by using this command

git clone https://github.com/RainyXeon/Cylane.git
git switch version-mongoose

**Comment by RainyXeon** [comment]
Because this is the BETA version of autofix lavalink and I forgot to move it into new branch so that why you get that error

Sorry

**Comment by RainyXeon** [comment]
Otherwise, you can disable it by set this one: `AUTOFIX_LAVALINK: false`

**Comment by onlinezc** [comment]
thank you
